import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import ProposalPreviewModal from "../AIDrafter/PreviewModel";
import { GenerateProposalPdf } from '../../../../services/techus-services';
import { showToast } from '../../../../genriccomponents/techus-ToastNotification';
import usePermissions from "../../../Common/usePermissions";
import { getPdfAssets } from '../../../../utils/pdfAssets';

const triggerDownload = (arrayBuffer, filename) => {
  const blob = new Blob([arrayBuffer], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.style.display = 'none';
  a.rel = 'noopener noreferrer';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 5000);
};

const HeaderSection = ({ nPages = 0, totalSections = 0, sections = [], selectedTemplate , proposalName = "",}) => {
  const navigate    = useNavigate();
  const projectUuid = localStorage.getItem("project_uuid");
  const { permissions } = usePermissions('proposal_drafter', 'contract_command');

  const [showPreview, setShowPreview]   = useState(false);
  const [exporting, setExporting]       = useState(false);
  const [previewLoading, setPreviewLoading] = useState(false);
  const [previewKey, setPreviewKey] = useState(0);
  const [activePreviewAssets, setActivePreviewAssets] = useState(null);

  // ── Pre-load assets on mount so they're ready instantly when modal opens ──
  const [pdfAssets, setPdfAssets] = useState({ coverBg: null, defaultLogo: null });
const resolvedProposalName = proposalName || "Proposal";

  useEffect(() => {
    getPdfAssets()
      .then(assets => setPdfAssets(assets))
      .catch(err => console.error("Failed to load PDF assets:", err));
  }, []);

  const goBack = () => {
    navigate(`/project/view/${projectUuid}/contract-command/proposal-drafter`);
  };

  const completedSections  = sections?.filter(s => s.loaded)?.length || 0;
  const generatingSections = sections?.filter(s => s.generating && !s.loaded)?.length || 0;
  const progressPercent    = totalSections > 0
    ? Math.round(((completedSections + generatingSections * 0.6) / totalSections) * 100)
    : 0;

  // ── Open preview — ensure assets are loaded first ─────────────────────────
  const handleOpenPreview = async () => {
    setPreviewLoading(true);
    try {
      const assets = pdfAssets.coverBg && pdfAssets.defaultLogo
        ? pdfAssets
        : await getPdfAssets();

      setPdfAssets(assets);
      setActivePreviewAssets(assets);
      setPreviewKey(prev => prev + 1);
      setShowPreview(true);
    } catch (err) {
      console.error("Asset load failed:", err);
      showToast('error', 'Failed to load preview assets. Please try again.');
    } finally {
      setPreviewLoading(false);
    }
  };

  const handleExport = async () => {
    setExporting(true);
    try {
      const { coverBg } = await getPdfAssets();
      const payload = {
        type: 'proposal',
        companyName: 'ACME INC.',
        coverBg,
        templateName: selectedTemplate || 'modern_blue',
        sections,
        footerNote: 'This proposal is generated by PrexoAI.',
        proposal_name: resolvedProposalName,
          proposalTitle: resolvedProposalName, 

        organization_id: localStorage.getItem('organization_id') || '',
      };
      const arrayBuffer = await GenerateProposalPdf(payload);
triggerDownload(arrayBuffer, `${resolvedProposalName}.pdf`);
    } catch (err) {
      console.error('Proposal PDF export failed:', err);
      showToast('error', 'Failed to export PDF. Please try again.');
    } finally {
      setExporting(false);
    }
  };

  return (
    <>
      <div className="tw-space-y-6 tw-py-4">
        {/* Top Nav Row */}
        <div className="tw-flex tw-justify-between tw-items-center tw-px-10">
          <div className="tw-flex tw-items-center tw-gap-4 tw-ml-[-45px]">
            <button
              onClick={goBack}
              className="tw-flex tw-items-center tw-justify-center tw-w-10 tw-h-10 tw-bg-[#b3bcce] tw-rounded-lg hover:tw-bg-[#0140c1] tw-transition-colors tw-duration-200"
            >
              <i className="icon-Previous tw-text-white tw-text-lg" />
            </button>
            <div>
              <div className="tw-text-[#002149] tw-text-[18px]">Proposal Drafter</div>
              <h1 className="tw-text-[#1e293b] tw-text-[14px] tw-font-normal">
                Review and customize your AI-generated proposal
              </h1>
            </div>
          </div>

          <div className="tw-flex tw-gap-3">
            {/* Preview button — waits for assets before opening */}
            <button
              onClick={handleOpenPreview}
              disabled={previewLoading}
              className="group tw-px-5 tw-py-2 tw-border tw-border-[#e2e8f0] tw-rounded-md tw-flex tw-items-center tw-gap-2 tw-bg-white tw-text-[#0f172a] tw-text-[14px] tw-font-medium
                tw-transition-all tw-duration-300 tw-ease-in-out
                hover:tw-bg-gray-50 hover:tw-shadow-lg hover:tw-shadow-gray-200/50
                hover:tw-scale-[1.03] hover:-tw-translate-y-[1px]
                active:tw-scale-[0.98] tw-whitespace-nowrap
                disabled:tw-opacity-60 disabled:tw-cursor-not-allowed"
            >
              {previewLoading
                ? <><svg className="tw-animate-spin tw-h-4 tw-w-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><circle className="tw-opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/><path className="tw-opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8H4z"/></svg>Loading…</>
                : <><i className="icon-Eye tw-text-lg tw-transition-transform tw-duration-300 group-hover:tw-translate-x-1" />Preview PDF</>
              }
            </button>

            {permissions?.export && (
              <button
                onClick={handleExport}
                disabled={exporting}
                className="group tw-px-5 tw-py-2 tw-bg-[#0140c1] tw-text-[14px] tw-font-medium tw-text-white tw-rounded-md tw-flex tw-items-center tw-gap-2
                  tw-transition-all tw-duration-300 tw-ease-in-out
                  hover:tw-bg-[#1b44c4] hover:tw-shadow-lg hover:tw-shadow-blue-200/50
                  hover:tw-scale-[1.03] hover:-tw-translate-y-[1px]
                  active:tw-scale-[0.98] tw-whitespace-nowrap
                  disabled:tw-opacity-60 disabled:tw-cursor-not-allowed disabled:tw-scale-100 disabled:tw-translate-y-0 disabled:tw-shadow-none"
              >
                {exporting ? (
                  <><svg className="tw-animate-spin tw-h-4 tw-w-4 tw-text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><circle className="tw-opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/><path className="tw-opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8H4z"/></svg>Exporting...</>
                ) : (
                  <><i className="icon-Export-PDF tw-text-lg"></i>Export Proposal</>
                )}
              </button>
            )}
          </div>
        </div>

        {/* Content Area */}
        <div className="tw-px-8 tw-flex tw-flex-col tw-gap-4">
          <div className="tw-bg-[#eaf2ff] tw-border tw-border-[#48f] tw-rounded-lg tw-p-5 tw-flex tw-gap-4">
            <div className="tw-text-[#4488ff] tw-text-3xl tw-bg-[#d9e7ff] tw-w-[59px] tw-h-[59px] tw-rounded-[15px] tw-flex tw-items-center tw-justify-center tw-flex-shrink-0">
              <i className="icon-Alert"></i>
            </div>
            <p className="tw-text-[15px] tw-text-[#1e293b] tw-leading-relaxed">
              We've carefully analyzed the uploaded RFP using advanced AI techniques and identified the key sections that require a response in your proposal. Based on the specific requirements outlined in each section, we've drafted tailored proposal content, which is provided below. Feel free to review, edit, or customize any section as needed, then export the final version as a PDF for submission.
            </p>
          </div>

          <div className="tw-flex tw-items-center tw-justify-between tw-bg-white tw-px-6 tw-py-4 tw-rounded-lg tw-border tw-border-[#e2e8f0]">
            <div className="tw-flex tw-gap-10 tw-items-center">
              <div className="tw-flex tw-items-center tw-gap-2">
                <i className="icon-Document-analysis tw-text-[#48f] tw-text-[20px]"></i>
                <span className="tw-text-[14px] tw-text-[#475569]">
                  <strong className="tw-text-gray-900 tw-font-bold">{nPages}</strong> pages analyzed
                </span>
              </div>
              <div className="tw-flex tw-items-center tw-gap-2">
                <i className="icon-list tw-text-[#48f] tw-text-[20px]"></i>
                <span className="tw-text-[14px] tw-text-[#475569]">
                  <strong className="tw-text-gray-900 tw-font-bold">{totalSections}</strong> sections identified
                </span>
              </div>
              <div className="tw-flex tw-items-center tw-gap-2">
                <i className="icon-Got-it tw-text-[#48f] tw-text-[20px]"></i>
                <span className="tw-text-[14px] tw-text-[#475569]">
                  <strong className="tw-text-gray-900 tw-font-bold">{completedSections}</strong> section completed
                </span>
              </div>
            </div>
            <div className="tw-flex tw-items-center tw-gap-4 tw-w-[30%]">
              <span className="tw-text-[13px] tw-font-bold tw-text-[#1e293b]">{progressPercent}%</span>
              <div className="tw-w-full tw-bg-[#f1f5f9] tw-rounded-full tw-h-2.5">
                <div className="tw-bg-[#0140c1] tw-h-2.5 tw-rounded-full tw-transition-all tw-duration-500" style={{ width: `${progressPercent}%` }}></div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* ── Preview Modal ── */}
      {showPreview && activePreviewAssets && (
        <ProposalPreviewModal
          key={previewKey}
          sections={sections}
          onClose={() => {
            setShowPreview(false);
            setActivePreviewAssets(null);
          }}
          templateName={selectedTemplate}
          proposalTitle={resolvedProposalName}
          companyName="ACME INC."
          companyLogo={activePreviewAssets.defaultLogo}
          coverBg={activePreviewAssets.coverBg}
        />
      )}
    </>
  );
};

export default HeaderSection;
